# 로컬(LOCAL) 환경 설정 파일 입니다.

# Spring boot Server Configuration
server:
  port: 8001

# Spring boot Basic Configuration
spring:

  # PostgreSQL DB Configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:

  # Thymeleaf Configuration
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html


